sudo: required  # see https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
language: python
python:
  - "3.4"
  - "3.5"  # I'm using a virtual environment with this version
  - "3.6"
install: "pip install -r requirements.txt"
services:
  - mongodb
script: pytest
notifications:
    email:
        on_success: change
        on_failure: always
after_sucess:
  - CODECLIMATE_REPO_TOKEN=c822878192484fde3cf9c98f68e97e19d53a4838a75d6cbce8b96466fce0308f codeclimate-test-reporter
